FROM ubuntu:25.10

RUN apt-get update && apt-get install -y --no-install-recommends \
  unminimize \
  ca-certificates \
  git \
  build-essential \
  cmake \
  ninja-build \
  pkg-config \
  libasio-dev \
  zlib1g-dev \
  libssl-dev \
  curl \
  xz-utils \
  python3 \
  python3-venv \
  python3-pip \
  unzip \
  build-essential \
  ripgrep \
  clangd \
  clang \
  lld \
  clang-format \
  libpqxx-dev \
  libpq-dev \
  postgresql-client \
  npm \
  zsh \
  fd-find \
  fzf \
  lazygit \
  wget \
  sqlite3 \
  trash-cli \
  locales \
  xclip \
  fish \
  imagemagick \
  ghostscript \
  && curl -fsSL -o /tmp/migrate.deb \
  https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.deb \
  && cd /tmp && apt-get install -y --no-install-recommends ./migrate.deb \
  && rm -f /tmp/migrate.deb \
  && rm -rf /var/lib/apt/lists/* \
  && yes | unminimize

RUN npm install -g neovim prettier markdownlint-cli2 @mermaid-js/mermaid-cli

RUN python3 -m pip install --break-system-packages pynvim sqlfluff

RUN git clone https://github.com/CrowCpp/Crow.git /tmp/Crow \
  && cmake -S /tmp/Crow -B /tmp/Crow/build \
  -DCROW_BUILD_EXAMPLES=OFF \
  -DCROW_BUILD_TESTS=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  && cmake --build /tmp/Crow/build \
  && cmake --install /tmp/Crow/build \
  && rm -rf /tmp/Crow

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz \
  && rm -rf /opt/nvim-linux-x86_64 \
  && tar -C /opt -xzf nvim-linux-x86_64.tar.gz

RUN git clone https://github.com/LazyVim/starter ~/.config/nvim

ENV PATH="/opt/nvim-linux-x86_64/bin:${PATH}"
ENV SHELL=/bin/zsh

WORKDIR /workspace/
